baseURL: 'https://loganlieou.github.io/website/'
languageCode: 'en-us'
title: "Jeboira"
author: "Logan Lieou"
theme: "hugo-PaperMod"

menu:
    main:
    - identifier: archive
      name: Archive
      url: "/archives"
    - identifier: resume
      name: Resume
      url: "/SWEResume.pdf"

params:
    homeInfoParams:
        Title: "Hello World"
        Content: "Nutted in your daughter you fuck"

    socialIcons: # optional
        - name: "Github"
          url: "https://github.com/LoganLieou"
        - name: "Twitter"
          url: "https://twitter.com/eeayor"
